#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 28 12:59:19 CET 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim BUTTON_UART_SIM_behav -key {Behavioral:sim_1:Functional:BUTTON_UART_SIM} -tclbatch BUTTON_UART_SIM.tcl -view /home/iwolfs/Work/Projects/fpga_project/xilinx/xilinx-experiments/UART_TX_RX_VER/BUTTON_UART_SIM_behav.wcfg -log simulate.log"
xsim BUTTON_UART_SIM_behav -key {Behavioral:sim_1:Functional:BUTTON_UART_SIM} -tclbatch BUTTON_UART_SIM.tcl -view /home/iwolfs/Work/Projects/fpga_project/xilinx/xilinx-experiments/UART_TX_RX_VER/BUTTON_UART_SIM_behav.wcfg -log simulate.log

